// Generated by CoffeeScript 2.7.0
var Item;

Item = (function() {
  class Item extends Backbone.Model {
    async render(location, units) {
      var res, self;
      self = {};
      res = (await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&APPID=cddbf0b42be47fe6061841ce93bf9ab6`, {
        method: "GET",
        mode: "cors"
      }));
      return res.json();
    }

  };

  Item.prototype.defaults = {
    data: []
  };

  return Item;

}).call(this);

export var ItemView = (function() {
  class ItemView extends Backbone.View {
    initialize() {
      return _.bindAll(this);
    }

    async updateLocation(location, units) {
      this.res = (await this.model.render(location, units));
      return this.res;
    }

    async addLocation(location, units) {
      this.res = (await this.model.render(location, units));
      return this.res;
    }

  };

  ItemView.prototype.model = new Item();

  return ItemView;

}).call(this);
